### ISSUE TITLE
Seeing memories from the previous day

### ISSUE THREAD

**Issue by keesjebal** [immichFrame/ImmichFrame#478]
### Version

latest

### Deployment Method

Android & Web

### Description

I'm having a Frameo frame. And already for a long time I keep seeing memories from the previous day. I'm still a bit trying to figure this out because it looks not consistent. Maybe it's related to my time-zone, but I don't know. It's both happening on the web- and Android-version (APK = v46).

I'm living in GMT+9:00 en my memories are from both +1:00 and +9:00. In Android and on the web I see old memories (from the previous day) in the morning. I tried to restart the container, but it still shows the old memories. I have GMT +9:00 configured as timezone for the container, my laptop and on the Frameo frame.

However, in my afternoon when I do a restart of the container I now see new memories. This is pretty strange. Could you please tell when the memories got refreshed and how this works?

### Reproduction

Wait till the next day. The next day you will see memories from the previous day.

### Expectations

Memories beging refresh on every new day.

### Configuration

```xml
services:
  immichframe_frameo:
    container_name: immichframe_p2284
    image: ghcr.io/immichframe/immichframe:latest
    volumes:
      - ./ImmichFrame_p2284:/app/Config
    ports:
      - "2284:8080"     
    env_file:
      - .env
  immichframe_extra:
    container_name: immichframe_p2285
    image: ghcr.io/immichframe/immichframe:latest
    volumes:
      - ./ImmichFrame_p2285:/app/Config
    ports:
      - "2285:8080"
    env_file:
      - .env



.env file contains:
TZ="Asia/Jayapura"


Settings.xml
{
  "General": {
    "AuthenticationSecret": null,
    "DownloadImages": false,
    "RenewImagesDuration": 30,
    "Webcalendars": [],
    "RefreshAlbumPeopleInterval": 12,
    "PhotoDateFormat": "d MMM ''yy",
    "ImageLocationFormat": "City",
    "WeatherApiKey": "",
    "UnitSystem": "metric",
    "WeatherLatLong": "51.8500,4.6611", 
    "Webhook": null,
    "Language": "en",
    "Margin": "0,0,0,0",
    "Interval": 30,
    "TransitionDuration": 0.5,
    "ShowClock": false,
    "ClockFormat": "HH:mm",
    "ShowProgressBar": true,
    "ShowPhotoDate": true,
    "ShowImageDesc": true,
    "ShowPeopleDesc": false,
    "ShowAlbumName": false,
    "ShowImageLocation": true,
    "PrimaryColor": "#FF5733",
    "SecondaryColor": "#000000",
    "Style": "transition",
    "BaseFontSize": "75px",
    "ShowWeatherDescription": false,
    "UnattendedMode": true,
    "ImageZoom": true,
    "ImagePan": false,
    "ImageFill": false,
    "Layout": "single"
  },
  "Accounts": [
    {
      "ImmichServerUrl": "http://172.17.0.1:2283",
      "ApiKey": "xxx",
      "ImagesFromDate": null,
      "ShowMemories": true,
      "ShowFavorites": false,
      "ShowArchived": false,
      "ImagesFromDays": null,
      "ImagesUntilDate": null,
      "Rating": null,
      "Albums": ["fe0a130d-c060-43cb-83e8-cfb9fb7618ad"],
      "ExcludedAlbums": [],
      "People": []
    }
  ]
}
```

### Logs

```shell
No relevant logs showing
```

### Pre-Submission Checklist

- [x] This is a bug report and not a feature request

- [x] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [x] I have checked for related issues and checked the documentation

**Comment by JW-CH** [comment]
This was already fixed with #442 but needs to be released. Wait for the next update :)

**Comment by keesjebal** [comment]
@JW-CH , today I installed the latest version, thanks! I completely removed the old container, so it should be fresh. However, I'm still seeing memories from the previous day. Today is the 13th and I see only memories from the 12th. So I'm wondering what is causing this. Any ideas? Thanks!


Btw: Sorry I tagged you. I'm unable to reopen the issue, so I thoughts to tag you. Thanks!

**Comment by 3rob3** [comment]
Working correctly for me. What TZ are you in? Is it set correctly?
I'm in U.S. EST though so it IS still the 12th.

**Comment by keesjebal** [comment]
I'm living in GMT+9:00. I have GMT +9:00 configured as timezone for the container, my laptop and on the Frameo frame.

**Comment by keesjebal** [comment]
I double checked the time inside the container and the time is OK:

<img width="596" height="90" alt="Image" src="https://github.com/user-attachments/assets/a3fe9d9d-1219-4241-8629-2aec6986bafd" />

**Comment by keesjebal** [comment]
Sorry for the spam :)
It's now 1:45PM here and I still saw memories from October 12th. I then did a restart of the container and now I see memories from the 13th. Maybe this is useful info.
Thanks again for checking on this!

**Comment by j-hugo** [comment]
@3rob3 I see this is closed but I am experiencing similar problems. I am seeing memories of the previous day, while today's date is displayed in the weather widget.

Timezone is set in my docker compose:
```yaml
    environment:
      TZ: 'Europe/Berlin'
```

Checking the date in the running docker container via `docker exec -t immichframe date` yields the correct date, however in the container logs I can see that the memories of the previous day are requested.

```
~ docker exec -t immichframe date
Sat Feb  7 11:55:20 CET 2026
```

```
26-02-07 11:50:29 info: System.Net.Http.HttpClient.ImmichApiAccountClient.LogicalHandler[100] Start processing HTTP request GET http://<immichhost>/api/memories?for=2026-02-06T23%3A00%3A00
```

Any thoughts how to fix this? Thanks!
